Add integration with Travis CI
kpi-web-guild/django-girls-blog-slsh1o pull request #18
Opened 2020-02-06 04:22 UTC by slsh1o

All seems to be ok.
Except:

> Add .travis.yml using pre-commit as a script. Set it up to run Python 3.8 env and add Pip caching. Ensure you install pre-commit before running tests: 

Here I just copy-pasted your code. Looks like it is what I actually should do but if something else let me know please.

@serhii73 let me know if it's ok that I add you to all my PRs. If it's to much I won't add you as frequently as I did it :D

Also traditionally ask for review @darklord671 and @ZVitaliy (darklord seems to switched off possibility to mention him😅)

Close #15

2020-02-06 10:30 UTC, serhii73 commented
> @serhii73 let me know if it's ok that I add you to all my PRs. If it's to much I won't add you as frequently as I did it :D

All good :+1:

2020-02-06 10:31 UTC, serhii73 commented
Excuse me @webknjaz 
Why Travis?
Why not GitHub actions?

2020-02-06 10:56 UTC, webknjaz commented
@serhii73 there's a lot of options, we cannot try all of them at once. Maybe later.

2020-02-06 10:59 UTC, webknjaz commented
@dark-lord671 changed the username

2020-02-06 16:10 UTC, webknjaz requested changes
Plz exclude commits that belong to the `features/pre-commit-integration` branch by rebasing on top of master.

Commit message improvements:

> Add Travis CI badge

*where to?*

Also:
```diff
-Add Travic CI config file
+Add Travis CI config file
```

2020-02-06 16:23 UTC, webknjaz commented on .travis.yml
> +script: pre-commit run --all-files
This'll fail once we start adding actual py files. But let's deal with it in a separate PR.

2020-02-10 22:47 UTC, slsh1o commented
If I will fix commits messages and than merge `features/pre-commit-integration` w/ master branch will it enough?

> Plz exclude commits that belong to the `features/pre-commit-integration` branch by rebasing on top of master.

I thought it's obvious where changes happens. Or if there are several commits in a row it would be better to add also explicit description in which file I add something?

_My text sounds a little rude but I really just want to know how to do it better😅_

> Commit message improvements:
> 
> > Add Travis CI badge
> 
> _where to?_

Can't find where this happened😅

> Also:
> 
> ```diff
> -Add Travic CI config file
> +Add Travis CI config file
> ```

2020-02-11 00:51 UTC, webknjaz commented
> If I will fix commits messages from #17 and than merge `features/pre-commit-integration` w/ master branch will it enough?
> 

You should reply after the quotes not before, preserving the natural order of messages.

In the case of merging #17, I'll still demand a rebase here.

> Can't find where this happened
> 

![commit-typo](https://user-images.githubusercontent.com/578543/74203379-b7fb4500-4c6f-11ea-9fe3-c26933bb5fa2.png)

> I thought it's obvious where changes happens. Or if there are several commits in a row it would be better to add also explicit description in which file I add something?

I'm not sure which quote this refers to but whenever you make a commit, it should be atomic and the reader should understand what it's about w/o looking into other places. You should maintain a good Git history for other humans and your future self, otherwise, it's hard to track the decisions and thought flows that lead to making them back to the past.

Imagine you see a piece of `git log` that looks like this:
```console
* fix
|
* Add Travis CI badge
|
* Fix Travis CI badge
|
* Add Travis CI badge
```
Can you say, w/o checking the contents of each commit, that the Travis CI badge was added to docs and to the README? What was fixed? Where?

2020-02-11 01:02 UTC, slsh1o commented
>You should reply after the quotes not before, preserving the natural order of messages.

Oh sorry, edited my message.

>Can you say, w/o checking the contents of each commit, that the Travis CI badge was added to docs and to the README? What was fixed? Where?

Now I got what you mean. Thx.

2020-02-11 01:14 UTC, webknjaz commented
P.S. It shouldn't necessarily be a full file name but it's good if it's a distinguishable pointer to some concrete place.

2020-02-11 02:25 UTC, slsh1o commented
Rebase this branch on top of master and make message of 4d9ca724 more clear.

2020-02-11 13:08 UTC, webknjaz commented
Could as well fix this:

> Add Travic CI config file

2020-02-11 13:10 UTC, webknjaz approved these changes

2020-02-11 16:17 UTC, merged