Add autorun step to travis.
kpi-web-guild/django-girls-blog-slsh1o pull request #30
Opened 2020-07-07 17:54 UTC by slsh1o

2020-07-07 21:27 UTC, webknjaz requested changes
It will have just one job unless you add some matrix expansion:
https://docs.travis-ci.com/user/build-matrix/#explicitly-included-jobs-with-only-one-element-in-the-build-matrix

Also, the PR title shouldn't end with a period. Plus the commit message should contain the summary, not repeat each and every line of the diff. Implementation details shouldn't be in the commit title — the commit itself already contains the implementation that is perfectly readable. What is the high-level effect of this commit? That's what the commit message title should answer.

2020-07-08 15:17 UTC, slsh1o commented
Ok now travis able to run tests but failed with empty secret key. Looks like I should implement #27 first.

2020-07-08 18:32 UTC, webknjaz requested changes
You may use https://docs.travis-ci.com/user/environment-variables/#defining-public-variables-in-travisyml to define some env vars for now.

2020-07-08 18:32 UTC, webknjaz commented on .travis.yml
> +  - 3.8
Don't use the same version twice

2020-07-09 18:46 UTC, webknjaz approved these changes

2020-07-09 18:48 UTC, merged